---
title: "rplot"
author: "Jince John"
date: '2022-04-05'
output: html_document
---
```{r}
library(tidyverse)
library(readxl)
```


```{r}
library(here)
```

```{r}
ca_np <- read.csv(here("data", "ca_np.csv"))

```
```{r}
names(ca_np)
head(ca_np)
```
```{r}
ci_np<- read_excel(here("data","ci_np.xlsx"))
```
```{r}
ggplot(data=ci_np, aes(x=year, y=visitors))+geom_line()
gg_base=ggplot(data=ci_np, aes(x=year, y=visitors))
gg_base+geom_point()
```
```{r}
gg_base+geom_point(
  color = "purple",
```


```{r}
gg_base + geom_point(
  aes(size=visitors,
      color=visitors),
  alpha=0.5
)
```


```{r}
?pch
```
```{r}
gg_base+geom_col(aes(fill=visitors))+theme_minimal()
```
```{r}
gg_base+geom_line(color="purple") +
  geom_point(color="orange", aes(size=year), alpha=0.5)
```
```{r}
ggsave(here("figures","ni_graph.jpg"), dpi=180, width=8, height = 7)
```
```{r}
ggplot(data = ca_np, aes(x = year, y = visitors, group = park_name)) +
  geom_line(show.legend = FALSE) +
  theme_light() + 
  labs(x = "year", y = "annual visitors") +
  facet_wrap(~ park_name)
```
```{r}
library(tidyverse)
library(readxl)
library(here)

```

```{r}
library(here)
```
```{r}
ca_np <- read.csv(here("data","ca_np.csv"))
ggplot(data=ca_np, aes(x=year, y=visitors, group =park_name))+ geom_line()
ca_nn <- ggplot(data=ca_np, aes(x=year, y=visitors, group =park_name))
ca_nn+ geom_line(show.legend = TRUE) +
  theme_light() + 
  labs(x = "year", y = "annual visitors") +
  facet_wrap(~ park_name)
```
```{r}
library(tidyverse)
library(readxl)
library(here)
```
```{r}
ggplot(data=ca_np, aes(x=year, y=visitors, group =park_name))+ geom_line(aes(color= park_name))+geom_point(aes(color="green"))
```

